// Code generated by mockery v2.14.0. DO NOT EDIT.

// Generated code. DO NOT MODIFY.

package sdk

import mock "github.com/stretchr/testify/mock"

// MockPlugin is an autogenerated mock type for the Plugin type
type MockPlugin struct {
	mock.Mock
}

// Configure provides a mock function with given fields: _a0
func (_m *MockPlugin) Configure(_a0 map[string]interface{}) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]interface{}) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: reqs
func (_m *MockPlugin) Get(reqs []*GetReq) ([]*GetResult, error) {
	ret := _m.Called(reqs)

	var r0 []*GetResult
	if rf, ok := ret.Get(0).(func([]*GetReq) []*GetResult); ok {
		r0 = rf(reqs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*GetResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]*GetReq) error); ok {
		r1 = rf(reqs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockPlugin interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockPlugin creates a new instance of MockPlugin. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockPlugin(t mockConstructorTestingTNewMockPlugin) *MockPlugin {
	mock := &MockPlugin{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
