// Code generated by mockery v1.0.0

// Generated code. DO NOT MODIFY.

package framework

import mock "github.com/stretchr/testify/mock"

// MockRoot is an autogenerated mock type for the Root type
type MockRoot struct {
	mock.Mock
}

// Configure provides a mock function with given fields: _a0
func (_m *MockRoot) Configure(_a0 map[string]interface{}) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]interface{}) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
