name: Reusable Go Version Workflow

on:
  workflow_call:
    outputs:
      go-version:
        description: "The Go version to use"
        value: ${{ jobs.get-go-version.outputs.go-version }}

jobs:
  get-go-version:
    name: "Determine Go toolchain version"
    runs-on: [ ubuntu-latest ]
    outputs:
      go-version: ${{ steps.get-go-version.outputs.go-version }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Determine Go version
        id: get-go-version
        # We use .go-version as our source of truth for current Go
        # version, because "goenv" can react to it automatically.
        run: |
          echo "Building with Go $(cat .go-version)"
          echo "go-version=$(cat .go-version)" >> $GITHUB_OUTPUT
